services:
  app:
    build: .
    image: my-java-app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/food_delivery
      DB_USER: fooddelivery_user
      DB_PASSWORD: fooddelivery_pass
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: fooddelivery_user
      POSTGRES_PASSWORD: fooddelivery_pass
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: