services:
  app:
    build: .
    image: my-java-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/food_delivery
      DB_USER: fooddelivery_user
      DB_PASSWORD: fooddelivery_pass
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/food_delivery
      SPRING_DATASOURCE_USERNAME: fooddelivery_user
      SPRING_DATASOURCE_PASSWORD: fooddelivery_pass
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/sql:/app/src/main/resources/sql

  db:
    image: postgres:15
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: fooddelivery_user
      POSTGRES_PASSWORD: fooddelivery_pass
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fooddelivery_user -d food_delivery"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: